apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app-chart.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ include "app-chart.name" . }}
