apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Release.Namespace | default "default" }}-quota
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
