apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ include "app-chart.name" . }}
