resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 256Mi
secret:
  greeting: "Hello from Leiden! <prd env>"
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
resourceQuota:
  enabled: true
  requestsCpu: "2"
  requestsMemory: 4Gi
  limitsCpu: "4"
  limitsMemory: 8Gi
